# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='state_abbrev',
            new_name='state',
        ),
    ]
