# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20160625_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
